### ISSUE TITLE
running on bash on windows 10 gives error

### ISSUE THREAD

**Issue by ali4ever4** [jarun/googler#179]
Hello i just tried this on bash on windows 10 and got the following error when try to do anything with googler

[ERROR] Failed to connect to www.google.com: [Errno 22] Invalid argument

can someone help ?

**Comment by zmwangx** [comment]
You've been given an issue template: https://github.com/jarun/googler/blob/master/.github/ISSUE_TEMPLATE.md. Please don't ignore it.

**Comment by ali4ever4** [comment]
ok thanks 

- Output of googler -d;

[DEBUG] Version 3.0
[DEBUG] Connecting to new host www.google.com
Traceback (most recent call last):
  File "/usr/bin/googler", line 682, in new_connection
    self._conn.connect(self._notweak)
  File "/usr/bin/googler", line 213, in connect
    sock.setsockopt(socket.SOL_TCP, socket.TCP_DEFER_ACCEPT, 1)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/googler", line 2357, in <module>
    main()
  File "/usr/bin/googler", line 2331, in main
    repl = GooglerCmd(opts)
  File "/usr/bin/googler", line 1703, in __init__
    notweak=opts.notweak)
  File "/usr/bin/googler", line 633, in __init__
    self.new_connection(host, port=port, timeout=timeout)
  File "/usr/bin/googler", line 685, in new_connection
    raise GoogleConnectionError(msg)
__main__.GoogleConnectionError: Failed to connect to www.google.com: [Errno 22] Invalid argument.

- Details of operating system
Windows 10 , bash , python version 2.7

**Comment by zmwangx** [comment]
That's guarded by a `sys.platform.startswith('linux')` conditional. I guess you're using Windows' Linux subsystem? Apparently they're not all the way there yet. I guess we can ignore errors from `setsockopt`.

> python version 2.7

googler doesn't work with Python 2.7. README:

> googler requires Python 3.3 or later.

**Comment by zmwangx** [comment]
#180. Please test if you wish.

**Comment by jarun** [comment]
#180 is merged now. Please test and confirm.

**Comment by ali4ever4** [comment]
thanks it works perfect now

**Comment by ali4ever4** [comment]
now need to find a way for it to understand how to open windows browser from linux subsystem bash -_- 

i guess that is still not possible in the current stable update of win 10 , not sure

**Comment by zmwangx** [comment]
> i guess that is still not possible in the current stable update of win 10 , not sure

It's not possible at the moment, because currently the Linux subsystem can't launch or talk to Win32 processes. I heard the bridge is coming in the Creators Update; in a fairly recent Microsoft demo they were able to launch nodepad++ from the Linux subsystem (don't want to look for the link now) and also talked about how VS talks to gcc and gdb on the Linux subsystem to directly build and debug ELF binaries for Linux. Anyway, I don't use Windows (except for specific gaming purposes...) and only follow Windows development very loosely, so I can't say when the support will come to CPython's `browser` module, which is what we use.

For now you should probably just install Python 3 on the Windows side and run googler there.

I'm closing this issue as solved.

**Comment by zmwangx** [comment]
> so I can't say when the support will come to CPython's browser module, which is what we use.

By the way, if you're concerned, you should probably search for this issue on https://bugs.python.org/, and create one if it isn't reported already.
