### ISSUE TITLE
Possible to do --json and non-exact?

### ISSUE THREAD

**Issue by smythp** [jarun/googler#184]
Currently, using --json implies exact, so if no results are returned Google won't substitute with another search term, you'll just get [ ]. Is it possible to get non-exact search with the --json flag enabled?

This is for a googler mode I'm making for Emacs, BTW. https://github.com/smythp/googler-mode Basic functionality is working if you'd like to try it out.

**Comment by zmwangx** [comment]
On second thought, `--json` implying `--exact` may be a bad decision on my part (bfcd5e153a15eb63c761426a0f2fc7efd9d71376). Users could always specify `--exact` otherwise, although it might take a few surprises to realize such.

Should `--json` continue to imply `--exact`, I have a hard time coming up with a satisfactory option (or a combination of options) to enable the behavior requested here, which is pretty reasonable. This is part of the reason for reverting bfcd5e153a15eb63c761426a0f2fc7efd9d71376.

I'll leave the decision to @jarun.

**Comment by smythp** [comment]
That would certain address my use case. Looking forward to hearing the decision.

**Comment by jarun** [comment]
No objection! Please go ahead and de-couple the two options.

**Comment by zmwangx** [comment]
#185.

**Comment by zmwangx** [comment]
Merged.
