### ISSUE TITLE
Add a proxy with authentication option

### ISSUE THREAD

**Issue by bobey** [jarun/googler#189]
It would be nice to allow Googler to query Google through an authenticated proxy.

At the moment, when I run something like `googler -p http://user:pwd@myproxy:port jarun` I get the following error:

```
[ERROR] Failed to connect to proxy server user:pwd@myproxy:port: [Errno -2] Name or service not known.
```

**Comment by bobey** [comment]
I quickly checked the current codebase and it seems that `HTTPSConnection` doesn't support proxy auth. Does it?

**Comment by zmwangx** [comment]
`HTTPSConnection` does support proxy authentication, at least basic auth. This is because `HTTPConnection.set_tunnel` has the `headers` options, and HTTP Basic Auth, in the context of proxy authentication, is nothing other than a `Proxy-Authorization` header. See [docs](https://docs.python.org/3/library/http.client.html#http.client.HTTPConnection.set_tunnel).

To give you a concrete example, say my username & password combo is `user:passwd`. `user:passwd` base64-encodes to `dXNlcjpwYXNzd2Q=`. Then I simply replace

```py
self._conn.set_tunnel(host, port=port)
```

with

```py
self._conn.set_tunnel(host, port=port, headers={'Proxy-Authorization': 'Basic dXNlcjpwYXNzd2Q='})
```

in the code and the proxy would let me in.

Could you please try to contribute this feature with a PR? Ideally we would support the same proxy specifications as curl, i.e.,

```
--proxy <[protocol://][user:password@]proxyhost[:port]>
```

where we only support the HTTP and HTTPS protocols.
