### ISSUE TITLE
UnicodeEncodeError in print() with KDE Konsole on KaOS

### ISSUE THREAD

**Issue by jarun** [jarun/googler#21]
The following error is thrown on KaOS when `googler` is invoked from KDE Konsole, (bash shell):

<pre>Our first program will print the classic Traceback (most recent call last):
  File "/usr/local/bin/googler", line 454, in <module>
    results = fetch_results()
  File "/usr/local/bin/googler", line 438, in fetch_results
    r.print_entry()
  File "/usr/local/bin/googler", line 203, in print_entry
    print(w, end=' ')
UnicodeEncodeError: 'ascii' codec can't encode character '\u201c' in position 0: ordinal not in range(128)</pre>
Fish shell works fine though.

**Comment by jarun** [comment]
To fix this issue, add the following in your `~/.bashrc`:
<pre>export PYTHONIOENCODING=UTF-8</pre>

**Comment by DerpDarako** [comment]
Hello, 

I tried to use your fix but it didn't help :

`[romain@b710l0701 ~]googler toto
Traceback (most recent call last):
  File "/usr/local/bin/googler", line 455, in <module>
    results = fetch_results()
  File "/usr/local/bin/googler", line 435, in fetch_results
    parser.feed(gzip.GzipFile(fileobj = StringIO.StringIO(resp.read())).read())
  File "/usr/lib64/python2.7/HTMLParser.py", line 117, in feed
    self.goahead(0)
  File "/usr/lib64/python2.7/HTMLParser.py", line 161, in goahead
    k = self.parse_starttag(i)
  File "/usr/lib64/python2.7/HTMLParser.py", line 308, in parse_starttag
    attrvalue = self.unescape(attrvalue)
  File "/usr/lib64/python2.7/HTMLParser.py", line 475, in unescape
    return re.sub(r"&(#?[xX]?(?:[0-9a-fA-F]+|\w{1,8}));", replaceEntities, s)
  File "/usr/lib64/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
[romain@b710l0701 ~]echo $PYTHONIOENCODING
UTF-8
`

**Comment by DerpDarako** [comment]
Hello,

I tried to use your fix but it didn't help :

```
[romain@b710l0701 ~]googler toto
Traceback (most recent call last):
  File "/usr/local/bin/googler", line 455, in <module>
    results = fetch_results()
  File "/usr/local/bin/googler", line 435, in fetch_results
    parser.feed(gzip.GzipFile(fileobj = StringIO.StringIO(resp.read())).read())
  File "/usr/lib64/python2.7/HTMLParser.py", line 117, in feed
    self.goahead(0)
  File "/usr/lib64/python2.7/HTMLParser.py", line 161, in goahead
    k = self.parse_starttag(i)
  File "/usr/lib64/python2.7/HTMLParser.py", line 308, in parse_starttag
    attrvalue = self.unescape(attrvalue)
  File "/usr/lib64/python2.7/HTMLParser.py", line 475, in unescape
    return re.sub(r"&(#?[xX]?(?:[0-9a-fA-F]+|\w{1,8}));", replaceEntities, s)
  File "/usr/lib64/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
[romain@b710l0701 ~]echo $PYTHONIOENCODING
UTF-8
[romain@b710l0701 ~]
```

**Comment by jarun** [comment]
Hi,

Can you please provide some more detail on this: OS, terminal emulator, shell used etc.?

**Comment by zmwangx** [comment]
I think @DerpDarako has an entirely different problem. He/she's getting `UnicodeDecodeError` from within `HTMLParser`. I haven't looked at the code closely, but I'd say it's probably a charset problem. It would help to know his/her region and locale, because I have no problem with `googler toto` in the U.S. (results are entirely ASCII — although I also have no problem with non-ASCII queries or results). Related: http://stackoverflow.com/q/4790078.

**Comment by jarun** [comment]
My bad, the issue was getting was from print(), as I copied above. We need this probably:
https://github.com/jarun/Buku/blob/master/buku#L397

Can you please submit a patch with this?
We can request @DerpDarako to reproduce it with the patch if we are not able to.

**Comment by zmwangx** [comment]
> Can you please submit a patch with this?

I think charset determination might not be so easy with PSL. The encoding reported by the request is of course — unhelpfully — `gzip`, so after gunzipping you have to somehow determine the charset yourself. There's of course the good ol' `chardet` library, but that's out of question because `googler` aims to not have extra dependencies (from my understanding). We can also manually parse the beginning of the HTML until the `meta charset` header, a segment that is basically guaranteed to be ASCII, but I'd say that's the last thing I would try.

On the other hand, I looked at Google's response from multiple regions, but all the responses have a `UTF-8` charset, despite different `lang`s. For instance, the response from `-c de` begins with

```html
<!doctype html><html itemscope="" itemtype="http://schema.org/SearchResultsPage" lang="de"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
```

and the response from `-c ja` begins with

```html
<!doctype html><html itemscope="" itemtype="http://schema.org/SearchResultsPage" lang="ja"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
```

so we have reason to believe Google always uses UTF-8 (and why would they not?).

So here's what I would propose:

1. Step 1, try to slap on a `.decode('utf-8')` in the Python 2.7.x case, which makes no difference for me anyway, but shouldn't hurt either:

    ```diff
diff --git a/googler b/googler
index c51d5fe..4993752 100755
--- a/googler
+++ b/googler
@@ -432,7 +432,7 @@ def fetch_results():
     if sys.version_info > (3,):
         parser.feed(gzip.GzipFile(fileobj = BytesIO(resp.read())).read().decode('utf-8'))
     else:
-        parser.feed(gzip.GzipFile(fileobj = StringIO.StringIO(resp.read())).read())
+        parser.feed(gzip.GzipFile(fileobj = StringIO.StringIO(resp.read())).read().decode('utf-8'))
 
     results = parser.results
     for r in results:
```

2. Step 2, if the above doesn't work, we should have a closer look at the response to see what's really going on:

    ```diff
diff --git a/googler b/googler
index c51d5fe..a85f78a 100755
--- a/googler
+++ b/googler
@@ -430,9 +430,11 @@ def fetch_results():
     parser = GoogleParser()
  
     if sys.version_info > (3,):
+        print(gzip.GzipFile(fileobj = BytesIO(resp.read())).read().decode('utf-8'))
         parser.feed(gzip.GzipFile(fileobj = BytesIO(resp.read())).read().decode('utf-8'))
     else:
-        parser.feed(gzip.GzipFile(fileobj = StringIO.StringIO(resp.read())).read())
+        print(gzip.GzipFile(fileobj = StringIO.StringIO(resp.read())).read().decode('utf-8'))
+        parser.feed(gzip.GzipFile(fileobj = StringIO.StringIO(resp.read())).read().decode('utf-8'))
 
     results = parser.results
     for r in results:
```

**Comment by jarun** [comment]
Understood. I will co-ordinate with @DerpDarako on this for the tests.
If required I'll deprecate the compression to be non-default option.

**Comment by DerpDarako** [comment]
Hi again,

Dunno if it can be useful :
```
[romain@b710l0701 ~]cat /etc/redhat-release 
Fedora release 23 (Twenty Three)
[romain@b710l0701 ~]env | grep TERM
TERM=xterm-256color
COLORTERM=xfce4-terminal
[romain@b710l0701 ~]env | grep bash
SHELL=/bin/bash
[romain@b710l0701 ~]locale
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```

**Comment by jarun** [comment]
Thanks again! I don't think this would affect the issue. The problem here is probably we are not checking the encoding of the input stream from google server and decoding it correctly.

**Comment by jarun** [comment]
I need to take a closer look. Will try to have something for you during the weekend.

**Comment by jarun** [comment]
@DerpDarako can you please enable the debug logs and paste the detailed output here? Try:
`$ googler -d toto`

**Comment by jarun** [comment]
In addition to the above, can you please check the results with Python 3.x as well? Doe that work for you?

**Comment by jarun** [comment]
@DerpDarako can you please test with the latest development version? The change applies to Python 2.7.x only. No modifications for Python 3.x.
If possible, please test with both Python 2.7 and Python 3.x and update the results.

As I am sending a UTF-8 request in the fetch string I am expecting this should work and I don't need to check if the response charset is in ascii or not.

**Comment by zmwangx** [comment]
@jarun Maybe we could do better at debug logging so that the response body is logged for further inspection? Here's a patch that does this: https://gist.github.com/anonymous/e5cc89568b658c03955d. It logs the response body to a tmpfile when debug is on, and on the console you'll see something like this:

```
> ./googler -d toto
[DEBUG] Base URL [/search?ie=UTF-8&oe=UTF-8&start=0&]
[DEBUG] Search URL [www.google.com : /search?ie=UTF-8&oe=UTF-8&start=0&q=toto]
[DEBUG] Response body written to '/Volumes/ramdisk/googler-response-oqY18e'.
```

And in `/Volumes/ramdisk/googler-response-oqY18e` you get the full HTML response body

```html
<!doctype html><html itemscope="" itemtype="http://schema.org/SearchResultsPage" lang="en"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type">...
```

This way a user could be asked to supply this body, which is a better reproducer than anything else, since Google apparently doesn't serve the same content to everyone in different regions.

If you like the patch you may directly apply it, or I could make a PR if you prefer it that way. If you don't like it please just ignore it. By the way, it's more idiomatic and controllable to use `logging.debug` for printing debugging info, but that's just a minor issue and a different discussion.

**Comment by jarun** [comment]
Please raise a PR, by all means. It's a valuable contribution and should remain yours.

**Comment by zmwangx** [comment]
I don't really feel entitled to a few lines of simple code, but since you asked, #27 it is.

**Comment by jarun** [comment]
The number of lines of code or how trivial they are is not important. In my experience, missing the MSB while copying from userspace to kernel space wrecked havoc in a OS for months. It was undetectable till we reached a particular memory usage level. So there you go!

In this case I liked the idea. As you might have read, I was particular about no "extra" disk file reads and writes (like config file). But I see no issues with debug logs.

Merged it. :)

**Comment by DerpDarako** [comment]
@jarun I did a new installation and it works using python 2.7.

Thank you :)

**Comment by jarun** [comment]
Thanks for the log. I could reproduce it with `-c fr` and it indeed got fixed with the patch. You will find this included in the next release.

Thanks @zmwangx for your help with this.

**Comment by jarun** [comment]
Fixed at https://github.com/jarun/googler/commit/49c247a62de79ed6c7ad7303d62bb0f215dfc2e8.
