### ISSUE TITLE
google scholar

### ISSUE THREAD

**Issue by rpietro** [jarun/googler#213]
hi, I am trying to set an alias for google scholar using .googler_at. here is what I tried:

>  alias @gs='googler -w scholar.google.com/scholar' # gives me an error
>  alias @gs='googler -w scholar.google.com'  # searches for people instead of the terms themselves

any thoughts on how to get it to work? thanks, this is a fantastic software

**Comment by zmwangx** [comment]
Unfortunately, Google Scholar search isn't a native functionality of googler. Only Search and News are supported.

**Comment by jarun** [comment]
However, from the received html data it seems googler can be extended to support it with some changes. If you are really interested, please raise a PR. We'll be glad to help out with the code understanding.

Tips:

`netloc` should be `www.scholar.google.com` and the path is `/scholar` instead of `/search`. These 2 changes, at the least, fetches the data you are looking for. Then you need to adapt the parser to handle scholarly results ;).

**Comment by jarun** [comment]
I have added it to the ToDo list. Please raise a PR directly if you implement it.

**Comment by zmwangx** [comment]
My detailed thoughts on why googler isn't equipped to handle Google Scholar can be found here: https://github.com/jarun/googler/issues/209#issuecomment-482767587.
