### ISSUE TITLE
Connection blocked error on searching anything

### ISSUE THREAD

**Issue by aksh1618** [jarun/googler#244]
I am using Googler in Arch (from AUR), and it was running fine until some days ago, I got 
```
[ERROR] Connection blocked due to unusual activity.
```

Now I get this for anything and everything I search for. Here's the debug output:
```
googler -d anything
[DEBUG] googler version 3.6
[DEBUG] Python version 3.7.0
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?ie=UTF-8&oe=UTF-8&q=anything
[DEBUG] Cookie: 1P_JAR=2018-08-11-11
Traceback (most recent call last):
  File "/usr/bin/googler", line 2575, in <module>
    main()
  File "/usr/bin/googler", line 2564, in main
    repl.cmdloop()
  File "/usr/bin/googler", line 2037, in cmdloop
    self.fetch_and_display()
  File "/usr/bin/googler", line 1718, in enforced_method
    method(self, *args, **kwargs)
  File "/usr/bin/googler", line 1884, in fetch_and_display
    self.fetch()
  File "/usr/bin/googler", line 1718, in enforced_method
    method(self, *args, **kwargs)
  File "/usr/bin/googler", line 1814, in fetch
    page = self._conn.fetch_page(self._google_url.relative())
  File "/usr/bin/googler", line 788, in fetch_page
    raise GoogleConnectionError('Connection blocked due to unusual activity.')
__main__.GoogleConnectionError: Connection blocked due to unusual activity.
```
Opening `google.com/search?ie=UTF-8&oe=UTF-8&q=anything` in firefox works fine. Tested on two different networks (ethernet and wifi), so it might be a cookie issue?

**Comment by jarun** [comment]
Are you behind a static IP or an ISP which is blocked by google?

**Comment by aksh1618** [comment]
The ethernet is static ip, but the WiFi isn't. Afaik, neither ISP is blocked by Google as it works fine in the browser.

**Comment by jarun** [comment]
are the following IP addresses same?

1. Search google for "my ip" in your browser
2. Run `curl ifconfig.me` from the terminal

**Comment by zmwangx** [comment]
Just open a fresh browser session (Incognito mode, private mode, guest profile, whatever) and see if you’re blocked.

**Comment by aksh1618** [comment]
@jarun Yes, they are same.
@zmwangx Just checked, not blocked.

**Comment by jarun** [comment]
@aksh1618 I am afraid we can't help further in this case.

In general when we see this error it's because of scripted usage in rapid succession (which is NOT the intention behind writing the utility, it's for convenience at the terminal). However, users have reported the block is removed if the internet connection is reset (when the device is assigned a new IP over DHCP). Personally I have seen this error and it gets unblocked after a while.

But as per the information provided by you it seems neither is the case and google still seems to detect you are using a non-standard request. I don't think we have a solution here.
