### ISSUE TITLE
"ERROR: Connection blocked due to unusual activity."

### ISSUE THREAD

**Issue by Jolg42** [jarun/googler#26]
Hi!

Do you know how to do a query without being blocked ? (It was my first cmd-line query…)

**Comment by jarun** [comment]
Please execute the query with the logs enabled and paste here. For example:
`$ googler -d my search string`

**Comment by jarun** [comment]
In addition, please share the browser URL when you run the same search in Google ( the usual web interface I mean).

**Comment by zmwangx** [comment]
I believe usually the way to go is to spoof the user agent and pretend you're a browser (user agent being `Python-urllib` sure is suspicious as hell because undisguised bots usually have user agents like this). Although based on my experience spoofing user agent won't guarantee success, especially if you use a VPN or make too many queries in a short period of time. (Hell, occasionally I get reCAPTCHA'ed just for using Incognito mode — that happens more often on YouTube but it's possible for Google Search too.)

**Comment by zmwangx** [comment]
By the way, if you get blocked on the command line, clearing a CAPTCHA in the browser (if available) usually fixes it.

**Comment by jarun** [comment]
That's true but long back there was an issue in the query (it was malformed) because of which I used to hit the same problem. Then I made some modifications to the query URL and that fixed it. Should be in the commit history but I am wondering why he hit it in the first go. We need to know the exact query that's outgoing and his country, any redirections etc. Faking a user agent is not a problem but this was fixed without any such problem. We need to compare the redirected/direct `googler` search URL to his browser search URL.

**Comment by zmwangx** [comment]
Yeah, the above was just a thought of mine; there could certainly be other causes. Plus having debug output is always nice for any issue. Actually, would you consider adding a issue template to remind users to always to include output of `googler -d`? See https://github.com/blog/2111-issue-and-pull-request-templates.

**Comment by jarun** [comment]
Here you go:
https://github.com/jarun/googler/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by zmwangx** [comment]
:+1: 

However, I'm not so sure about checklists. While checklists are nice, there are at least two major flaws:

1. Many casual GitHub users don't know how to edit GFM checklists;

2. To me, checklists should only be used when absolutely necessary, to indicate progress towards completion of various goals. And GitHub has this nice feature that lets you see with a glance the checklist completion stats on the issue/PR screen. Using checklists in the issue template breaks that mechanic and makes the feature a lot less useful.

Since there are only four items in total, it's quite unlikely that users will need to physically tick each one off to be sure that they haven't missed anything. So my suggestion is to use a plain list. Just a thought to consider.

**Comment by jarun** [comment]
Now they don't have to do it. But it looks cool! ;) I CAN'T remove those :P.

**Comment by zmwangx** [comment]
It's your project so of course you have the final say. I get it that checklists look cool, but they'll eventually suck when you get something like this (corresponding to my point 1):

<img width="775" alt="screen shot 2016-02-20 at 12 01 29 am" src="https://cloud.githubusercontent.com/assets/4149852/13195370/4b8c7cc8-d765-11e5-9cea-4114525e60af.png">

or this (corresponding to my point 2):

<img width="556" alt="screen shot 2016-02-20 at 12 01 57 am" src="https://cloud.githubusercontent.com/assets/4149852/13195372/52718114-d765-11e5-82a1-638f233d4c4e.png">

(Screenshots taken from Homebrew.)

**Comment by jarun** [comment]
I must say I see the point.

**Comment by jarun** [comment]
@Jolg42, this might also happen if you are connecting via tor. All Google requests are blocked and need captcha pass.

**Comment by Jolg42** [comment]
Hi @jarun & @zmwangx !

So here is the debug :
```
[DEBUG] Base URL [/search?ie=UTF-8&oe=UTF-8&start=0&]
[DEBUG] Search URL [www.google.com : /search?ie=UTF-8&oe=UTF-8&start=0&q=duckduckgo]
[DEBUG] Redirected URL [https://ipv4.google.com/sorry/IndexRedirect?continue=https://www.google.com/search%3Fie%3DUTF-8%26oe%3DUTF-8%26start%3D0%26q%3Dduckduckgo&q=CGMSBFGrax4YueKwtgUiGQDxp4NLf7mfUDId6-YEsIU8gH4kw1LUXQk]
ERROR: Connection blocked due to unusual activity.
``` 
I also tested by going to `google.com/search?ie=UTF-8&oe=UTF-8&start=0&q=duckduckgo` in my browser. So I cleared the captcha here and retried with the cmd line but same error… I redid the copy paste search in my browser and I wasn't blocked by a captcha that time.

I think it's something with the User Agent, so is it possible to customize it ?

**Comment by zmwangx** [comment]
Try disguising as, say, Microsoft Edge:

```diff
diff --git a/googler b/googler
index 33acfe2..ceb9e40 100755
--- a/googler
+++ b/googler
@@ -57,6 +57,8 @@ skipped = 0       # Count for skipped ads or blank links
 debug = False     # Print debug logs
 news = False      # Read news
 server = "www.google.com"
+ua = ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
+      '(KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240')
 
 
 # Classes
@@ -388,7 +390,7 @@ def fetch_results():
             print("[DEBUG] Exception: %s" % e)
         conn.close()
         conn = HTTPSConnection(server, timeout=45)
-        conn.request("GET", url, None, {"Accept-encoding": "gzip"})
+        conn.request("GET", url, None, {"Accept-encoding": "gzip", "User-Agent": ua})
         resp = conn.getresponse()
 
     if resp.status != 200:
```

I don't have too much have in it though, because I just used this trick on Travis and failed: https://travis-ci.org/zmwangx/googler/builds/111177736. However, I spammed thousands of requests an hour ago, so I'd say the block on me was legit; YMMV.

**Comment by jarun** [comment]
Something that's still not clear to me: why would it fail for him every time? There's nothing unusual in the query and it's the same as mine. @Jolg42, would you mind explaining a bit more on your use-case?

Were you sending too many queries in succession?
Is every query failing?
Did you run a number of Google queries (from browser) a while before this failure?
Are you behind a proxy, or Tor?

@zmwangx the Travis integration is awesome! ;)

**Comment by zmwangx** [comment]
> the Travis integration is awesome! ;)

Would have been awesome if I weren't blocked :sob:

**Comment by jarun** [comment]
I've pushed your user agent modifications for all requests just now (at https://github.com/jarun/googler/commit/b595687a03bfc2d24d14ba28cb55f6bf5abc9ee5). Please retry with that.

**Comment by jarun** [comment]
For me it passed all 100 tests. No issues. Ran from India but there were no server redirection other than with .com.

**Comment by jarun** [comment]
@Jolg42 can you please try the latest development version?
In addition, we need the information below:

Were you sending too many queries in succession?
Is every query failing?
Did you run a number of Google queries (from browser) a while before this failure?
Are you behind a proxy, or Tor?
Anything else you think might have been unusual?

**Comment by zmwangx** [comment]
> I've pushed your user agent modifications for all requests just now

I'd argue it's a dirty hack... But okay.

**Comment by jarun** [comment]
Yes, I'm still not sure what caused this issue for @Jolg42. Will wait for his results and any other details he might provide.

**Comment by Jolg42** [comment]
Hi :)
The update is perfect :+1: It's now working!
![screenshot 2016-02-25 at 18 14 27](https://cloud.githubusercontent.com/assets/1328733/13327812/ba847484-dbeb-11e5-835f-31c4d0de67a1.jpg)

So just to follow up with your last questions :

_Were you sending too many queries in succession?_
No my first query was blocked

_Is every query failing?_
Yes

_Did you run a number of Google queries (from browser) a while before this failure?_
No

_Are you behind a proxy, or Tor?_
No, but coworking WiFi

_Anything else you think might have been unusual?_
No

But everything's fine now the User-Agent is helping on my side!

**Comment by jarun** [comment]
Good news! Thanks for confirming.

@zmwangx you mentioned issues with Travis setup earlier... was that fixed with addition of UA agent?

**Comment by jarun** [comment]
@zmwangx I can [Travis failures](https://travis-ci.org/jarun/googler/builds/111820237) due to the same reason. How about making the number of queries 25 per test?

**Comment by zmwangx** [comment]
>  you mentioned issues with Travis setup earlier... was that fixed with addition of UA agent?

No, that was due to spamming thousands of request. I have fixed that by introducing a limit on the number of tests we run.

> I can Travis failures due to the same reason.

Probably just got unlucky that single time, I'd say let's just ignore it.

> How about making the number of queries 25 per test?

Since we're running randomized tests over many servers and many languages (I just noticed I actually left out a whole lot of TLDs in the script, will push a fix), 25 is just a bit too low to catch errors. For instance, if you run the test on 03a5316 (pre decoding UTF-8 on Python 2.7 — have to cherry pick first 4bc14dd to make googler work with the test script), you'll see that the test script almost always fail for 100 tests, but there's a high chance of passing 25 consecutive tests.

**Comment by zmwangx** [comment]
@jarun I consider this issue resolved, and am closing. If we are to discuss non-user-facing problems (), let's open a new thread to avoid spamming the OP.

Actually I just opened a [gitter chatroom](https://gitter.im/jarun/googler), which could be a slightly better place for discussing problems that are not worth opening issue threads.

**Comment by zmwangx** [comment]
Or we can also open a Slack channel if that's your thing.

**Comment by jarun** [comment]
I'll open an issue solely for our discussion. Let's keep it simple.
