### ISSUE TITLE
issue with tmux 3.0a

### ISSUE THREAD

**Issue by ghistes** [jarun/googler#333]
Hi,

I am not really sure if this is a googler issue (as opposed to a tmux issue) but I've recently upgraded to tmux 3.0a and googler does not work anymore as it did with previous tmux-versions:

What happens is that when I run googler in a vertically split window (one pane above and one pane below) I do not see the usual googler output (a blank line followed by the seach-results) but instead the output starts with the description of the first search result  (so it seems the first 3 lines of the normal output are missing).

This also happens with the current master.

googler -d
[DEBUG] googler version 4.0
[DEBUG] Python version 3.8.2
[DEBUG] Connecting to new host www.google.com

**Comment by jarun** [comment]
I do see results with tmux split:

```
~$ g hello world  
                                                     │
                                                     │ 1.  "Hello, World!" program - Wikipedia [en.wikipedi
                                                     │a.org]
                                                     │     A "Hello, World!" program generally is a
                                                     │     computer program that outputs or displays the
                                                     │     message "Hello, World!". Such a program is
                                                     │     very simple in most ...
                                                     │
                                                     │ 2.  Hello, World! - Learn Python - Free Interactive 
                                                     │Python Tutorial [www.learnpython.org]
                                                     │     Hello, World! Python is a very simple
                                                     │     language, and has a very straightforward
                                                     │     syntax. It encourages programmers to program
                                                     │     without boilerplate (prepared) ...
                                                     │
                                                     │ 3.  Hello World · GitHub Guides [guides.github.com]
                                                     │     Apr 7, 2016
                                                     │     What is GitHub? Create a Repository; Create a
                                                     │     Branch; Make a Commit; Open a Pull Request;
                                                     │     Merge Pull Request. The Hello World
                                                     │     project ...
                                                     │
                                                     │ 4.  The History of 'Hello, World' - HackerRank Blog 
                                                     │[blog.hackerrank.com]
                                                     │     Apr 21, 2015
                                                     │     Where does 'Hello World' come from? Brian
                                                     │     Kernighan, author of one of the most widely
                                                     │     read programming books, "C Programming
                                                     │     Language", ...
                                                     │
                                                     │ 5.  HelloWorld Coliving, Student Hostels & Coworking
                                                     │ Spaces [thehelloworld.com]
                                                     │     Hello World provides coliving, student
                                                     │     housing, coworking, social spaces and natural
                                                     │     habitats to those exploring the evolution of
                                                     │     humanity through positive ...
                                                     │
                                                     │ 6.  Hello, world! - JavaScript.info [javascript.info
                                                     │]
                                                     │     Mar 29, 2020
                                                     │     p > < script > alert ( 'Hello, world!' ) ; </
                                                     │     script > < p > ...After the script. </ p > </
                                                     │     body > </ html >. You can run the example by
                                                     │     clicking the “Play” ...
                                                     │
                                                     │googler (? for help)
```

I think it's a tmux issue if you are seeing description of the first result (meaning results are fetched). tmux is not knpwn to be the best renderer out there. My vim theme changes when I use it on tmux.

Check your tmux config please.

**Comment by jarun** [comment]
And if it is indeed a problem with 3.0a please get back to your earlier version. That's the best I can say.

**Comment by nicm** [comment]
This sounds most likely to be a problem with your terminal emulator rather than tmux. Is it Konsole? Try this in `.tmux.conf`:
~~~~
set -as terminal-overrides '*:indn@'
~~~~
If this doesn't help, best bet is to open a tmux issue.

Incorrect colours for vim inside tmux are usually a result of incorrect `TERM` inside or outside tmux, or failure to configure tmux so it knows the terminal outside supports RGB colour (see [here](https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-rgb-colour)), or failure to configure same for vim (t_8f/t_8b IIRC). As a relatively new feature, many systems still lack the right flags in their terminfo database to let tmux detect this automatically, and even in those that do most terminals still use for example `xterm-256color` instead of `xterm-direct`. If it isn't that, best bet is to open a tmux issue.

**Comment by zmwangx** [comment]
> so it seems the first 3 lines of the normal output are missing

Sounds like scrolling to me? ...

googler is not a TUI program, it doesn't use any termcap other than color sequences. So missing lines indicates one of the following:

- Regular scrolling; just scroll it back...
- CR somehow mixed into the output. You can check with xxd, but I highly doubt we're somehow printing three CRs in the first three lines.
- Messed up terminal emulation. Since we don't use any termcap as I said, I'd be astonished if tmux could mess up something this basic.

Anyway, this is just a boring CLI program without any terminal rendering trickery. The only time we query the terminal at all is `os.get_terminal_size` to determine line wrapping: https://github.com/jarun/googler/blob/140f4d0bd28dbf143c801c339cbd490bf4dc54ed/googler#L2413 which is a standard PSL function.
