### ISSUE TITLE
Cmdline not working with Windows cmd.exe

### ISSUE THREAD

**Issue by phamwon** [jarun/googler#358]
All cmdline does not apply when I run on cmd.exe, but when tested on Windows PowerShell, it runs very well.

![image](https://user-images.githubusercontent.com/3305093/88455550-61419a80-cea0-11ea-9f34-e9ddf1ac61a3.png)

**Comment by zmwangx** [comment]
Can't reproduce with googler installed [through choco](https://chocolatey.org/packages/googler). 

![image](https://user-images.githubusercontent.com/4149852/88455678-e4b3b980-cea9-11ea-995c-b3d5a029664d.png)

Also, this looks like a generic Python script problem. Start with something simple like placing `argv.py`

```py
import sys

print(sys.argv)
```

on your `PATH` and see if it works.

Since neither of the maintainers here use Windows much, we probably won't be of much help.

**Comment by phamwon** [comment]
Thanks for help, that worked when add `print(sys.argv)` !
