### ISSUE TITLE
homebrew

### ISSUE THREAD

**Issue by sammcj** [jarun/googler#5]
it would be great if this could be added to @homebrew !

**Comment by jarun** [comment]
Thank you for the suggestion! We have a set of ongoing changes. We'll try to take this up once those are stabilized.

**Comment by jarun** [comment]
Hi,

We can look into homebrew now. I have a few questions:

1. What are the advantages? Does it make the utility installation distro independent? Currently google-cli has minimal requirements and most of the Python libs it needs are core ones installed by default.

2. Is homebrew installation by itself heavy? By number of packages I mean.

3. Would you mind making the necessary changes if you are already familiar? Otherwise, I can take a look into it.

**Comment by ibaaj** [comment]
Your formula, according to the [Formula Cookbook](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md) is something like this class : 

```ruby
class Googler < Formula
  desc "Google from the commandline"
  url "https://github.com/jarun/google-cli/archive/v1.8.tar.gz"
  homepage "https://github.com/jarun/google-cli"
  sha256 "a4d4d1a3dd3086736f10ba2958215455bc7c6558c5785627cef8b743b6085833"
  
  depends_on :python => :build if MacOS.version <= :snow_leopard

  def install
    system "make", "install"
  end
end
```

**Comment by garymoon** [comment]
@jarun Googler is great stuff!

I've added myself as a watcher, which should allow googler to fulfill the notability requirement (>=10 forks, >=10 watchers and >=20 stars).

@ibaaj your formula lgtm, let me know if I can be of help.

**Comment by jarun** [comment]
Thank you! Wouldn't have been possible without an awesome community.
I would be more than happy to accept any patches on this.

**Comment by garymoon** [comment]
Oh bugger, I didn't realize how old this was ("I only just discovered this tool and thought it should go in homebrew, so of course ditto for everyone else derpy derp derp"). If @ibaaj doesn't respond in the next day or so I'll have a go at it myself, but be forewarned I've never submitted anything to homebrew in the past myself.

**Comment by jarun** [comment]
That's absolutely fine :). Have a go!

**Comment by ibaaj** [comment]
```ruby
class Googler < Formula
  desc "Google from the commandline"
  url "https://github.com/jarun/googler/archive/master.zip"
  homepage "https://github.com/jarun/googler"
  sha256 "01e8114f92893e8e0d06bad4e809ba87769e245692ae35826bef3f6c26348e7d"

  depends_on :python => :build if MacOS.version <= :snow_leopard

  def install
    system "make", "install"
  end
end
```

sha256 proprety must be updated each time you modify anything

**Comment by jarun** [comment]
Please submit as a patch.

**Comment by garymoon** [comment]
That won't be accepted. There will always be a gap between a commit to master and updating the formula, during which time anyone who attempts to install will suffer breakage. If you'd like people to be able to run directly from master, you can include a "head" property with a direct link to the git repo, which will allow people to specify `--head` to get a build from master:

     head "https://github.com/jarun/googler.git"

For a standard install, it will pull the tar from the specified release.

After looking at the makefile I'm not sure that will be accepted either. Taking a look at a similarly trivial formula for `ssh-copy-id` [here](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/ssh-copy-id.rb), I think we probably want to use `bin.install` and `man1.install`.

My current take on the formula would be:

```ruby
class Googler < Formula
  desc "Google from the commandline"
  url "https://github.com/jarun/googler/archive/v2.1.tar.gz"
  homepage "https://github.com/jarun/googler"
  sha256 "4f42325b3961efa19c475138507f156891c27db7882ed6f75dfa256aef63016c"
  head "https://github.com/jarun/googler.git"
  version "2.1"

  bottle :unneeded

  depends_on :python => :build if MacOS.version <= :snow_leopard

  def install
    bin.install "googler"
    man1.install "googler.1"
  end
end
```

Please let me know your thoughts.

**Comment by ibaaj** [comment]
So, I prefer to let others (@garymoon ?) do the pull request.

**Comment by garymoon** [comment]
Some further reading of [acceptable formulae](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md) and [how to get your PR merged](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-%28and-get-it-merged%29.md) give me some pause.

Beyond the hard requirements I mentioned above there seems to be a few softer requirements that are largely subjective to the reviewer - do they _feel_ the formula will be well maintained, do they _feel_ the project will not be abandoned any time soon. I wonder if, given the small install base of googler, whether or not they will be convinced.

They also frown upon author's submitting their own work, so if we proceed I will fork homebrew and submit the PR directly.

Please have a skim of the documents I linked above and let me know what you think @jarun.

**Comment by jarun** [comment]
@ibaaj, @garymoon, I will take a look into this. Might take some time for me to respond back.

**Comment by garymoon** [comment]
No problem @jarun :)

**Comment by jarun** [comment]
Thanks @ibaaj and @garymoon for spending your valuable time and helping me out on this. To begin with, had I been the reviewer, I wouldn't accept googler for 2 very simple reasons:
- it's (an useful but) a tiny tool and is not written in the canonical python format, with clearly distinguished classes, "submodules" etc. Blame it on my C background, I don't care much beyond treating a scripting language for what it's worth. Yes, the code is easy to follow and modify but that's about it. We don't even have a `setup.py` around for Christ's sake! ;)
- googler doesn't have any dependencies other than core python. It's a single file. What does homebrew and pip have to do with it really?
  
If it's about ease of installation, at least on Ubuntu and Arch, we don't need to install a single extra package. Any random visitor can clone googler repo (or download the file raw) and run it. That's documented as well. Why would we want to modify a hash every time we commit a minor change to the code? Sometimes I forget to change the version and date while making a new release... this adds to my pain.
  
I am very particular about the dependency thing and will try to maintain 0-dependency as long as it's not inevitable. I don't see that happening anytime soon.
  
Please let me know what you think. Otherwise let's close this one off.

**Comment by garymoon** [comment]
I'm not sure I see the issue in either of your points, they both sound fine to me.

Homebrew is intended primarily as a convenience for OS X users, much as pip is for Python users except that Homebrew is primarily for utilities and tools - googler is a pretty good example of what would be included in homebrew.

I agree googler would be an odd thing to put in pip (since it's not usable as a library).

Updating the hash isn't necessary any longer. A standard googler install would install the tar from the latest formula (with a hash check) and you can install directly from git with `--head`. The formula would only need periodic updating with a major release, and only at the maintainers leisure.

I don't see any issue maintaining the zero-dependency status. Homebrew isn't a dependency, unless you count updating the formula periodically (which would be done by someone else).

I'm not pressuring or anything, I'm happy to accept an answer of "this isn't my bag, baby", just clarifying some points is all.

**Comment by garymoon** [comment]
It's a bit hard to explain the relevance of homebrew to someone not on OS X. I suppose without Homebrew OS X is a little like having a linux distro without a package manager, and having to rely on static builds available online (like Windows).

**Comment by jarun** [comment]
Understood. This link explains a lot: http://docs.python-guide.org/en/latest/starting/install/osx/  
I wanted some assurance from the Python side of it ;). The last question I had was: if I can install Python without Homebrew, what gives?  
However, as I can see from the above link, there are benefits.

**Comment by garymoon** [comment]
I think I might be missing part of the disconnect here. What would installing python through homebrew have to do with googler in homebrew?

**Comment by jarun** [comment]
I was thinking from the point of ease of running googler` on OSX. If Python core can be installed easily on OSX (without Homebrew) or comes by default, getting the `googler` script and running it is quite easy. However, as I understood from the link, the version of Python that ships with OSX might be outdated as well and then Homebrew comes to the rescue.
Basically what I wanted to figure out is, do we really need a package manager to run the googler script? After the read, I think Homebrew keeps things saner.

**Comment by garymoon** [comment]
To me it's not about dependency management or anything like that. I prefer not to be responsible for maintaining the software on my system - that's what a package manager is for.

Are you of the mind we should proceed?

**Comment by jarun** [comment]
Yes, I understand your perspective. :)
Please proceed.

**Comment by jarun** [comment]
Hi Gary,

Any update on this?

**Comment by zmwangx** [comment]
Hi, I happened to have discovered this project earlier today and immediately submitted it to Homebrew, without knowledge of this thread (I only found this when I came to report an issue). Progress can be tracked here: https://github.com/Homebrew/homebrew/pull/49331. Submitting a formula to Homebrew isn't a big deal, it'll either be accepted or rejected, no hurt feelings either way, so there's really no need for much debate. If accepted I'll be responsible for keeping the formula updated soon after each release (I already keep several other formulae updated), so there won't be any burden here.

**Comment by jarun** [comment]
Thank you so much! I guess Gary took a detour ;).

**Comment by zmwangx** [comment]
No problem :)

**Comment by zmwangx** [comment]
https://github.com/Homebrew/homebrew/pull/49331 has been merged, so this issue could probably be closed.

**Comment by jarun** [comment]
Thank you very much! Can you please update the README with the Homebrew installation steps?

**Comment by zmwangx** [comment]
My pleasure. Added to the list of installation methods in #25.

**Comment by jarun** [comment]
Closing the issue.

**Comment by garymoon** [comment]
I'm so sorry @jarun. I was on a business trip in Europe until yesterday and it kind of monopolized my time. I need to sort out my GitHub notifications too - way too much crap in there I don't care about so I get notification fatigue.

Awesome stuff @zmwangx, I noticed it in there when I updated homebrew just now. Great work!

**Comment by jarun** [comment]
@garymoon I knew it had to do something with a "tour" ;).
Yes, @zmwangx is cool! He was actively fixing `googler` issues when I was in office yesterday. It's good to have guys like you around :).

**Comment by garymoon** [comment]
As you can tell by my swift reply, I pulled my head out of my ass and immediately fixed my GH notifications.

Again I really am sorry about that. Hopefully I can be of help in the future.

**Comment by jarun** [comment]
No problem at all! I hope you had a fruitful and safe trip.
You helped a lot by changing my perception of homebrew. Vital contributions don't always need to translate into code ;).

**Comment by garymoon** [comment]
Thanks @jarun, the trip went very well :)

I'm glad you're now a homebrew fan :D I really can't imagine using OS X without it.
